version: '3.4'

services:
  php:
    build:
      context: .
      target: sylius_temporarily_out_of_stock_plugin_php
    image: nedac/sylius_temporarily_out_of_stock_plugin_php:latest
    environment:
      - APP_ENV=test
      - DATABASE_URL=mysql://sylius:temporarily_out_of_stock@127.0.0.1:3306/sylius_temporarily_out_of_stock
    volumes:
      - .:/srv/sylius
    network_mode: host

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sylius_temporarily_out_of_stock
      - MYSQL_USER=sylius
      - MYSQL_PASSWORD=temporarily_out_of_stock
    ports:
      - "3306:3306"
    network_mode: host

  nginx:
    build:
      context: .
      target: sylius_temporarily_out_of_stock_plugin_nginx
    image: nedac/sylius_temporarily_out_of_stock_plugin_nginx:latest
    volumes:
      - .:/srv/sylius
    ports:
      - "8080:8080"
    network_mode: host

  nodejs:
    build:
      context: .
      target: sylius_temporarily_out_of_stock_plugin_nodejs
    image: nedac/sylius_temporarily_out_of_stock_plugin_nodejs:latest
    environment:
      - GULP_ENV=dev
    volumes:
      - .:/srv/sylius
    network_mode: host

  chrome:
    build:
      context: .
      target: sylius_temporarily_out_of_stock_plugin_chrome
    image: nedac/sylius_temporarily_out_of_stock_plugin_chrome:latest
    ports:
      - "9222:9222"
    network_mode: host
